import 'package:dart_json_mapper/dart_json_mapper.dart';

@jsonSerializable
@Json(enumValues: Emoji.values)
enum Emoji {
  THINKING_FACE,
  GRINNING_FACE_WITH_SMILING_EYES,
  SMILING_FACE_WITH_HEART_EYES,
  HEAR_NO_EVIL_MONKEY,
  UNAMUSED_FACE,
  DROOLING_FACE,
  LOUDLY_CRYING_FACE,
  SLEEPING_FACE,
  YAWNING_FACE,
  FACE_WITH_TEARS_OF_JOY,
  DOWNCAST_FACE_WITH_SWEAT,
  POUTING_FACE,
  PILE_OF_POO,
  NERD_FACE,
  FACE_WITH_MEDICAL_MASK,
  FACE_SCREAMING_IN_FEAR,
  PANDA,
  PERSON_IN_LOTUS_POSITION,
  PERSON_LIFTING_WEIGHTS,
  EXPLODING_HEAD,
}
